### ISSUE TITLE
Feature Request: Year range

### ISSUE THREAD

**Issue by kruncher** [monooso/dropdate.ee_addon#3]
Fantastic add-on for ExpressionEngine. It would be really nice if there was an option to specify years from a given start value to the current year.

I can think of two good ways to implement this:
1. A tick box.
2. Specify the range as "1900-"

**Comment by manifestuk** [comment]
Hi Lee,

You already can; just enter `1900-now`.

There is a new version of DropDate (which was never released), that you can download from the `develop` branch. Among many other things (including better handling of timezones) it includes easier input for date ranges.

The only caveat is that the new DropDate (on `develop`) is not backwards-compatible with previous versions. As such, if you've already got a load of DropDate data in your site, it may not be worth the hassle of upgrading.

Cheers,
Stephen

**Comment by kruncher** [comment]
Many thanks that's fantastic. I have added this to the WIKI documentation for you.

Would it be worth creating a new branch from the master branch called "DropDateV1" and then merging the development branch into the master branch?

**Comment by manifestuk** [comment]
Hi Lea,

> I have added this to the WIKI documentation for you.

Thanks. I've added [a few extra bits](https://github.com/experience/dropdate.ee_addon/wiki/Field-Configuration-Instructions) about relative dates, which may be of interest to you.

> Would it be worth creating a new branch from the master branch called "DropDateV1" and then merging the development branch into the master branch?

I'm really not keen on doing that, because the new version isn't backward compatible. Somebody could notice the new version, update their site, and corrupt or lose a load of DropDate data.

In order for it to become an "official" release, I'd need to be confident that the above situation couldn't happen; either that or bump the major version number, announce the non-backward compatibility, and hope nobody hoses their site by accident.

Given that very few people seem to read documentation, and even fewer read the release notes, the latter solution doesn't appeal.

The simplest solution is for me to write some code to migrate old data to the new format. This isn't a massive technical hurdle, but equally it's not something I have time for at the moment, particularly as I've long-since stopped writing EE add-ons for a living.

I've contacted a couple of add-on devs I respect, to see if they fancy officially adopting DropDate. We'll see how that goes.

Cheers,
Stephen

**Comment by kruncher** [comment]
> Thanks. I've added a few extra bits about relative dates, which may be of interest to you.

Sweet thanks for doing that. I can already put those relative dates to good use!

> I'm really not keen on doing that, because the new version isn't backward compatible. Somebody could notice the new version, update their site, and corrupt or lose a load of DropDate data.

Yeah I fully understand that from my own experiences of add-on development for a different software package.
